#ifndef LIGHTGBM_APPLICATION_H_
#define LIGHTGBM_APPLICATION_H_


#include <LightGBM/meta.h>
#include <LightGBM/config.h>
#include <string>
#include <vector>
#include <memory>
namespace LightGBM {

//class DatasetLoader;
//class Dataset;
//class Boosting;
//class ObjectiveFunction;
//class Metric;

/*!
* \brief The main entrance of LightGBM. this application has two tasks:
*        Train and Predict.
*        Train task will train a new model
*        Predict task will predict the scores of test data using exsisting model,
*        and save the score to disk.
*/
class Application {
public:
	explicit Application()
	{
		;
	}
  Application(int argc, char** argv);

  /*! \brief Destructor */
  virtual ~Application();

  /*! \brief To call this funciton to run application*/
  inline void Run();

public:

  /*! \brief Load parameters from command line and config file*/
  void LoadParameters(int argc, char** argv);

  /*! \brief Load data, including training data and validation data*/
  void LoadData();

  /*! \brief Initialization before training*/
  void InitTrain();

  /*! \brief Main Training logic */
  void Train();

  /*! \brief Initializations before prediction */
  void InitPredict();

  /*! \brief Main predicting logic */
  void Predict();

  /*! \brief Main Convert model logic */
  void ConvertModel();

  /*! \brief All configs */
  Config config_;
  /*! \brief Training data */
  std::unique_ptr<Dataset> train_data_;
  /*! \brief Validation data */
  std::vector<std::unique_ptr<Dataset>> valid_datas_;
  /*! \brief Metric for training data */
  std::vector<std::unique_ptr<Metric>> train_metric_;
  /*! \brief Metrics for validation data */
  std::vector<std::vector<std::unique_ptr<Metric>>> valid_metrics_;
  /*! \brief Boosting object */
  std::unique_ptr<Boosting> boosting_;
  /*! \brief Training objective function */
  std::unique_ptr<ObjectiveFunction> objective_fun_;
};


inline void Application::Run() {
  if (config_.task == TaskType::kPredict || config_.task == TaskType::KRefitTree) {
    InitPredict();
    Predict();
  } else if (config_.task == TaskType::kConvertModel) {
    ConvertModel();
  } else {
    InitTrain();
    Train();
  }
}
#pragma region OnlineApp

/*!
* \brief The main entrance of LightGBM. this application has two tasks:
*        Train and Predict.
*        Train task will train a new model
*        Predict task will predict the scores of test data using exsisting model,
*        and save the score to disk.
* And OnlineApp is based on Application Class. And we can use the official lightgbm version to train a model, all we have to do is
* to implemant the predict model.
* OnlineApp is derived from Application class.
*/
class OnlineApp :public Application
{
public:
	/*constractor with model_file,this file is generated by train mudule.*/
	OnlineApp(char * model_filename, char *config_file);
	void InitPredict();
	void Predict(std::vector<std::string>& vector_datas, int label_index, std::vector< std::vector<double> >& result);
	~OnlineApp()
	{
		;
	}
private:
	std::string input_model ;
	//Predictor * predictor;//Later we should use smart point,such as auto_ptr<>¡¤¡¤¡¤
};

#pragma endregion
}  // namespace LightGBM

#endif   // LightGBM_APPLICATION_H_
